# ----------------------------------------------------------------------------
# Copyright (c) 2021-2026 DexForce Technology Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------

import torch
from typing import Dict, Optional, Tuple

from embodichain.lab.gym.envs import EmbodiedEnv, EmbodiedEnvCfg
from embodichain.lab.gym.utils.registration import register_env
from embodichain.utils import logger
from robosynchallenge.managers.events import visualize_rigid_body_pose
from embodichain_tasks.tableware.base_agent_env import BaseAgentEnv
from .action_bank import (
    WaterPouringActionBank,
)

__all__ = ["WaterPouringEnv", "WaterPouringTestEnv", "WaterPouringAgentEnv"]


@register_env("WaterPouring", max_episode_steps=600)
class WaterPouringEnv(EmbodiedEnv):
    def __init__(self, cfg: EmbodiedEnvCfg = None, **kwargs):
        super().__init__(cfg, **kwargs)
        # initialize pouring state flags for all envs
        try:
            self._pouring_started = torch.zeros(
                self.num_envs, dtype=torch.bool, device=self.device
            )
            self._pouring_completed = torch.zeros(
                self.num_envs, dtype=torch.bool, device=self.device
            )
        except Exception:
            # Fallback: initialize on CPU if device not ready yet
            self._pouring_started = torch.zeros(self.num_envs, dtype=torch.bool)
            self._pouring_completed = torch.zeros(self.num_envs, dtype=torch.bool)

        action_config = kwargs.get("action_config", None)
        if action_config is not None:
            self.action_config = action_config

    def reset(self, seed: Optional[int] = None, options: Optional[Dict] = None):
        """Reset environment and pouring state flags."""
        obs, info = super().reset(seed=seed, options=options)
        # ensure flags are reset on environment reset
        self._pouring_started = torch.zeros(
            self.num_envs, dtype=torch.bool, device=self.device
        )
        self._pouring_completed = torch.zeros(
            self.num_envs, dtype=torch.bool, device=self.device
        )
        return obs, info

    def create_demo_action_list(self, *args, **kwargs):
        """
        Create a demonstration action list for the current task.

        Returns:
            list: A list of demo actions generated by the task.
        """
        logger.log_info("Create demo action list for WaterPouringTask.")

        if getattr(self, "action_config") is not None:
            self._init_action_bank(WaterPouringActionBank, self.action_config)
            action_list = self.create_expert_demo_action_list(*args, **kwargs)
        else:
            logger.log_error("No action_config found in env, please check again.")

        if action_list is None:
            return action_list

        logger.log_info(
            f"Demo action list created with {len(action_list)} steps.", color="green"
        )
        return action_list

    def create_expert_demo_action_list(self, **kwargs):
        """
        Create an expert demonstration action list using the action bank.

        This function generates a trajectory based on expert knowledge, mapping joint and end-effector
        states to the required action format for the environment and robot type.

        Args:
            **kwargs: Additional keyword arguments.

        Returns:
            list: A list of actions, each containing joint positions ("qpos").
        """

        if hasattr(self, "action_bank") is False or self.action_bank is None:
            logger.log_error(
                "Action bank is not initialized. Cannot create expert demo action list."
            )

        ret = self.action_bank.create_action_list(
            self, self.graph_compose, self.packages
        )

        if ret is None:
            logger.log_warning("Failed to generate expert demo action list.")
            return None

        # TODO: to be removed, need a unified interface in robot class
        left_arm_joints = self.robot.get_joint_ids(name="left_arm", remove_mimic=True)
        right_arm_joints = self.robot.get_joint_ids(name="right_arm", remove_mimic=True)
        left_eef_joints = self.robot.get_joint_ids(name="left_eef", remove_mimic=True)
        right_eef_joints = self.robot.get_joint_ids(name="right_eef", remove_mimic=True)


        total_traj_num = ret[list(ret.keys())[0]].shape[-1]
        num_active_joints = len(self.active_joint_ids)
        actions = torch.zeros(
            (total_traj_num, self.num_envs, num_active_joints), dtype=torch.float32
        )

        
        global_to_active_idx = {
            joint_id: active_idx for active_idx, joint_id in enumerate(self.active_joint_ids)
        }

        for key, joints in [
            ("left_arm", left_arm_joints),
            ("left_eef", left_eef_joints),
            ("right_arm", right_arm_joints),
            ("right_eef", right_eef_joints),
        ]:
            if key in ret:
                # TODO: only 1 env supported now
                local_action_data = torch.as_tensor(ret[key].T, dtype=torch.float32)

                
                for i, joint_id in enumerate(joints):
                    if joint_id in global_to_active_idx:
                        active_idx = global_to_active_idx[joint_id]
                        actions[:, 0, active_idx] = local_action_data[:, i]
        return actions

 
    def _evaluate_task_state(self) -> Tuple[torch.Tensor, torch.Tensor, Dict]:
        bottle = self.sim.get_rigid_object("bottle")
        cup = self.sim.get_rigid_object("cup")

        bottle_final_xpos = bottle.get_local_pose(to_matrix=True)
        cup_final_xpos = cup.get_local_pose(to_matrix=True)

        bottle_fall = self._is_fall_y(bottle_final_xpos)
        cup_fall = self._is_fall_z(cup_final_xpos)

        bottle_up = bottle_final_xpos[:, :3, 2]
        world_z = torch.tensor([0.0, 0.0, 1.0], dtype=bottle_up.dtype, device=bottle_up.device)
        dot = torch.sum(bottle_up * world_z, dim=-1)
        dot = torch.clamp(dot, -1.0, 1.0)
        bottle_angle = torch.acos(dot)
        bottle_angle_deg = bottle_angle * 180.0 / torch.pi

        bottle_over_cup = torch.ones(self.num_envs, dtype=torch.bool, device=bottle_final_xpos.device)

        bottle_in_pour_range = (bottle_angle_deg > 70.0) & (bottle_angle_deg < 100.0)

        # update pouring state: once started stays started
        try:
            self._pouring_started = self._pouring_started | bottle_in_pour_range
            self._pouring_completed = self._pouring_started
        except Exception:
            # if flags are not present for some reason, initialize them
            self._pouring_started = torch.zeros(
                self.num_envs, dtype=torch.bool, device=bottle_final_xpos.device
            ) | bottle_in_pour_range
            self._pouring_completed = self._pouring_started

        success = (
            self._pouring_completed
            & (~bottle_fall)
            & (~cup_fall)
        )

        # Require the action graph to have reached the 'stand' skill for right_arm
        try:
            stand_required = True
            # find the scheduled end time for the 'stand' edge for right_arm
            stand_end = None
            if hasattr(self, "packages") and self.packages is not None:
                for p in self.packages.get("packages", []):
                    if p.get("label") == "stand" and p.get("legend") == "right_arm":
                        stand_end = p.get("end")
                        break

            if stand_end is not None and hasattr(self, "_elapsed_steps"):
                stand_reached = self._elapsed_steps >= int(stand_end)
            else:
                # if we don't have schedule or elapsed info, be conservative and do not allow success
                stand_reached = False

            success = success & stand_reached
        except Exception:
            # on any error, conservatively disable success until stand is reached
            success = success & torch.zeros_like(success)
        fail = cup_fall

        try:
            N_PROTECT_STEPS = 150
            if hasattr(self, "_elapsed_steps"):
                elapsed = self._elapsed_steps
                early_mask = elapsed < N_PROTECT_STEPS
                success = success & (~early_mask)
        except Exception:
            pass

        info = {
            "bottle_angle_deg": bottle_angle_deg,
            "bottle_in_pour_range": bottle_in_pour_range,
            "pouring_started": self._pouring_started,
            "pouring_completed": self._pouring_completed,
            "bottle_fall": bottle_fall,
            "cup_fall": cup_fall,
        }

        return success, fail, info
    
    
    def is_task_success(self, **kwargs) -> torch.Tensor:
        success, _, _ = self._evaluate_task_state()
        return success

    def _is_fall_y(self, pose: torch.Tensor) -> torch.Tensor:
        # Extract z-axis from rotation matrix (last column, first 3 elements)
        pose_rz = pose[:, :3, 1]
        world_z_axis = torch.tensor([0, 0, 1], dtype=pose.dtype, device=pose.device)

        # Compute dot product for each batch element
        dot_product = torch.sum(pose_rz * world_z_axis, dim=-1)  # Shape: (batch_size,)

        # Clamp to avoid numerical issues with arccos
        dot_product = torch.clamp(dot_product, -1.0, 1.0)

        # Compute angle and check if fallen
        angle = torch.arccos(dot_product)
        return angle >= torch.pi / 4
    def _is_fall_z(self, pose: torch.Tensor) -> torch.Tensor:
        # Extract z-axis from rotation matrix (last column, first 3 elements)
        pose_rz = pose[:, :3, 2]
        world_z_axis = torch.tensor([0, 0, 1], dtype=pose.dtype, device=pose.device)

        # Compute dot product for each batch element
        dot_product = torch.sum(pose_rz * world_z_axis, dim=-1)  # Shape: (batch_size,)

        # Clamp to avoid numerical issues with arccos
        dot_product = torch.clamp(dot_product, -1.0, 1.0)

        # Compute angle and check if fallen
        angle = torch.arccos(dot_product)
        return angle >= torch.pi / 4


@register_env("WaterPouringTest", max_episode_steps=600)
class WaterPouringTestEnv(WaterPouringEnv):
    def compute_task_state(self, **kwargs):
        _, fail, _ = self._evaluate_task_state()
        return torch.zeros(self.num_envs, dtype=torch.bool), fail, None

    def is_task_success(self, **kwargs) -> torch.Tensor:
        success, _, _ = self._evaluate_task_state()
        return torch.ones_like(success, dtype=torch.bool)

@register_env("WaterPouringAgent", max_episode_steps=600)
class WaterPouringAgentEnv(BaseAgentEnv, WaterPouringEnv):
    def __init__(self, cfg: EmbodiedEnvCfg = None, **kwargs):
        super().__init__(cfg, **kwargs)
        super()._init_agents(**kwargs)

    def reset(self, seed: Optional[int] = None, options: Optional[Dict] = None):
        obs, info = super().reset(seed=seed, options=options)
        super().get_states()
        return obs, info
